source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Sudden_Example', :exclusive => true do
  pod "Sudden", :path => "../"
end

target 'Sudden_Tests', :exclusive => true do
  pod "Sudden", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
